Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "ansible/inventory.yml"
        ansible.playbook = "ansible/playbook.yml"
  end
end